apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hacbs-test-project-t1au
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hacbs-test-project-t1au
    app.kubernetes.io/part-of: integ-app-fjfe
  name: hacbs-test-project-t1au
spec:
  replicas: 0
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hacbs-jvm-build-test-project
      app.kubernetes.io/instance: hacbs-test-project-t1au
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hacbs-jvm-build-test-project
        app.kubernetes.io/instance: hacbs-test-project-t1au
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/nbe-e2e-qkhg-tenant/integ-app-fjfe/hacbs-test-project-t1au@sha256:ea3b14e058792d73f7ebb84d8952f465da6da77e6e26ac2cebbe6e4c8c83d439
        name: hacbs-jvm-build-test-project
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
